language: cpp

env:
  global:
  - PATH=/tmp/bin:$PATH
  - CMAKE_CXX_FLAGS="-Wpedantic -Wall -Wextra"

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env: CXX=g++-8
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-6.0
        - ubuntu-toolchain-r-test
        packages:
        - clang-6.0
        - g++-8
    env: CXX=clang++-6.0
  - os: linux
    env: CXX=clang++ LIBCXX_VERSION=6.0.0
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-7
        - ubuntu-toolchain-r-test
        packages:
        - clang-7
        - g++-8
    env: CXX=clang++
  - os: linux
    env: CXX=clang++ LIBCXX_VERSION=7.0.0
  - os: osx
    compiler: clang
    addons:
      homebrew:
        packages:
        - cmake
        update: true

before_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis/install_cmake.sh; fi
- |
  if [ -n "$LIBCXX_VERSION" ]; then
    travis/install_clang.sh ${LIBCXX_VERSION}
    CMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS -stdlib=libc++"
    CMAKE_EXE_LINKER_FLAGS=-lc++abi
  fi

script:
- cmake -E make_directory build
- cmake -E chdir build cmake .. -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS" -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS"
- cmake --build build -j 2

notifications:
  email: false
