language: cpp
dist: xenial

env:
  global:
  - PATH=/tmp/bin:$PATH
  - CMAKE_CXX_FLAGS="-Wpedantic -Wall -Wextra"

matrix:
  include:
  - os: osx
    compiler: clang
    addons:
      homebrew:
        packages:
        - cmake
        update: true
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - MATRIX_EVAL="CXX=g++-8"
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - MATRIX_EVAL="CLANG_VERSION=6.0.0"
  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="CLANG_VERSION=6.0.0 && USE_LIBCXX=1"
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="USE_LIBCXX=1"

before_script:
- eval "${MATRIX_EVAL}"
- |
  if [ -n "$CLANG_VERSION" ]; then
    travis/install_clang.sh ${CLANG_VERSION}
  fi
  if [ -n "$USE_LIBCXX" ]; then
    CMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS -stdlib=libc++"
    CMAKE_EXE_LINKER_FLAGS=-lc++abi
  fi

script:
- cmake -E make_directory build
- cmake -E chdir build cmake .. -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS" -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS"
- cmake --build build -j 2

notifications:
  email: false
